var fs = require('fs');
var path = require('path');
var readline = require('readline');

var TYPES_FILE = path.join(__dirname, 'src', 'index.ts');
var PLACEHOLDER_MARKER = 'types not generated yet';

function findProjectRoot() {
  var dir = path.dirname(__dirname);
  while (true) {
    var pkgPath = path.join(dir, 'package.json');
    if (fs.existsSync(pkgPath) && !pkgPath.replace(/\\/g, '/').includes('/node_modules/')) {
      return dir;
    }
    var parent = path.dirname(dir);
    if (parent === dir) return process.cwd();
    dir = parent;
  }
}

function getConfigPath() {
  return path.join(findProjectRoot(), 'pyrpc-client.json');
}

var TYPE_MAP = {
  int: 'number',
  float: 'number',
  str: 'string',
  bool: 'boolean',
  None: 'null',
  NoneType: 'null',
  Any: 'any',
};

function toTs(t) {
  if (!t || t === 'None') return 'void';
  var m = t.match(/^<class\s+'([^'>]+)'>$/);
  if (m) {
    var n = m[1];
    if (TYPE_MAP[n]) return TYPE_MAP[n];
    if (n[0] >= 'A' && n[0] <= 'Z') return n;
    return 'any';
  }
  var s = t.replace(/^typing\./, '');
  var o = s.match(/^Optional\[(.+)\]$/);
  if (o) return toTs(o[1]) + ' | null';
  var l = s.match(/^(?:List|list)\[(.+)\]$/);
  if (l) return toTs(l[1]) + '[]';
  var d = s.match(/^(?:Dict|dict)\[([^,]+),\s*(.+)\]$/);
  if (d) return 'Record<' + toTs(d[1]) + ', ' + toTs(d[2]) + '>';
  var u = s.match(/^Union\[(.+)\]$/);
  if (u) return u[1].split(',').map(function(p) { return toTs(p.trim()); }).join(' | ');
  var tup = s.match(/^(?:Tuple|tuple)\[([^\]]+)\]$/);
  if (tup) return '[' + tup[1].split(',').map(function(p) { return toTs(p.trim()); }).join(', ') + ']';
  return 'any';
}

function generate(schemas) {
  var lines = [];
  lines.push('// Auto-generated by @pyrpc/types');
  lines.push('// Schema fetched from: ' + (process.env.PYRPC_URL || 'http://localhost:8000'));
  lines.push('');
  var names = Object.keys(schemas);
  for (var i = 0; i < names.length; i++) {
    var name = names[i];
    var schema = schemas[name];
    lines.push('export interface ' + name + 'Params {');
    var params = schema.parameters || [];
    for (var j = 0; j < params.length; j++) {
      var p = params[j];
      lines.push('  ' + p.name + ': ' + toTs(p.type) + ';');
    }
    lines.push('}');
    lines.push('');
    lines.push('export interface ' + name + 'Result {');
    lines.push('  data: ' + toTs(schema.return_type) + ';');
    lines.push('}');
    lines.push('');
  }
  lines.push('export interface Types {');
  for (var k = 0; k < names.length; k++) {
    lines.push('  ' + names[k] + ': { params: ' + names[k] + 'Params; result: ' + names[k] + 'Result };');
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function fetchSchema(url) {
  var endpoint = url.replace(/\/+$/, '');
  if (endpoint.indexOf('/rpc') !== endpoint.length - 4) {
    endpoint += '/rpc';
  }
  if (typeof fetch !== 'undefined') {
    return fetch(endpoint).then(function(res) {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return res.json();
    });
  }
  var mod = url.indexOf('https') === 0 ? require('https') : require('http');
  return new Promise(function(resolve, reject) {
    mod.get(endpoint, function(res) {
      var data = '';
      res.on('data', function(c) { data += c; });
      res.on('end', function() {
        if (res.statusCode !== 200) return reject(new Error('HTTP ' + res.statusCode));
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(e); }
      });
    }).on('error', reject);
  });
}

function main() {
  if (fs.existsSync(getConfigPath())) {
    return Promise.resolve();
  }

  var isInteractive = process.stdin.isTTY;
  var isCI = process.env.CI;

  if (!isInteractive || isCI) {
    return Promise.resolve();
  }

  var rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(function(resolve) {
    rl.question('How are types distributed to the client?\n  1) workspace (default) - server writes types directly to your project\n  2) server - client fetches types via HTTP\nEnter choice [1]: ', function(answer) {
      rl.close();
      resolve(answer.trim() === '2' ? 'server' : 'workspace');
    });
  }).then(function(distribution) {
    if (distribution === 'workspace') {
      var config = { distribution: 'workspace' };
      fs.writeFileSync(getConfigPath(), JSON.stringify(config, null, 2) + '\n');
      console.log('  \u2713 pyrpc-client.json created (workspace mode)');
      return;
    }

    var rl2 = readline.createInterface({ input: process.stdin, output: process.stdout });
    return new Promise(function(resolve) {
      rl2.question('pyRPC backend URL (default: http://localhost:8000): ', function(answer) {
        rl2.close();
        resolve(answer.trim() || 'http://localhost:8000');
      });
    }).then(function(url) {
      return fetchSchema(url).then(function(schemas) {
        var code = generate(schemas);
        fs.mkdirSync(path.dirname(TYPES_FILE), { recursive: true });
        fs.writeFileSync(TYPES_FILE, code, 'utf-8');
        console.log('  \u2713 @pyrpc/types: generated for ' + Object.keys(schemas).length + ' procedures');

        var config = { distribution: 'server', server_url: url };
        fs.writeFileSync(getConfigPath(), JSON.stringify(config, null, 2) + '\n');
        console.log('  \u2713 pyrpc-client.json created (server mode)');
      }).catch(function(err) {
        console.log('  \u2717 @pyrpc/types: could not connect (' + err.message + ')');
        console.log('  Run later: npx pyrpc sync');

        var config = { distribution: 'server', server_url: url };
        fs.writeFileSync(getConfigPath(), JSON.stringify(config, null, 2) + '\n');
        console.log('  \u2713 pyrpc-client.json created (server mode)');
      });
    });
  });
}

if (require.main === module) {
  main().catch(function(e) {});
}

module.exports = { main, toTs, generate, fetchSchema, findProjectRoot, getConfigPath, TYPES_FILE, PLACEHOLDER_MARKER };
