var fs = require('fs');
var path = require('path');
var readline = require('readline');

var TYPES_FILE = path.join(__dirname, 'src', 'index.ts');
var PLACEHOLDER_MARKER = 'types not generated yet';

// Skip if real types already exist
if (fs.existsSync(TYPES_FILE)) {
  var content = fs.readFileSync(TYPES_FILE, 'utf-8');
  if (!content.includes(PLACEHOLDER_MARKER)) {
    process.exit(0);
  }
}

var TYPE_MAP = {
  int: 'number',
  float: 'number',
  str: 'string',
  bool: 'boolean',
  None: 'null',
  NoneType: 'null',
  Any: 'any',
};

function toTs(t) {
  if (!t || t === 'None') return 'void';
  var m = t.match(/^<class\s+'([^'>]+)'>$/);
  if (m) {
    var n = m[1];
    if (TYPE_MAP[n]) return TYPE_MAP[n];
    if (n[0] >= 'A' && n[0] <= 'Z') return n;
    return 'any';
  }
  var s = t.replace(/^typing\./, '');
  var o = s.match(/^Optional\[(.+)\]$/);
  if (o) return toTs(o[1]) + ' | null';
  var l = s.match(/^(?:List|list)\[(.+)\]$/);
  if (l) return toTs(l[1]) + '[]';
  var d = s.match(/^(?:Dict|dict)\[([^,]+),\s*(.+)\]$/);
  if (d) return 'Record<' + toTs(d[1]) + ', ' + toTs(d[2]) + '>';
  var u = s.match(/^Union\[(.+)\]$/);
  if (u) return u[1].split(',').map(function(p) { return toTs(p.trim()); }).join(' | ');
  var tup = s.match(/^(?:Tuple|tuple)\[([^\]]+)\]$/);
  if (tup) return '[' + tup[1].split(',').map(function(p) { return toTs(p.trim()); }).join(', ') + ']';
  return 'any';
}

function generate(schemas) {
  var lines = [];
  lines.push('// Auto-generated by @pyrpc/types');
  lines.push('// Schema fetched from: ' + (process.env.PYRPC_URL || 'http://localhost:8000'));
  lines.push('');
  var names = Object.keys(schemas);
  for (var i = 0; i < names.length; i++) {
    var name = names[i];
    var schema = schemas[name];
    lines.push('export interface ' + name + 'Params {');
    var params = schema.parameters || [];
    for (var j = 0; j < params.length; j++) {
      var p = params[j];
      lines.push('  ' + p.name + ': ' + toTs(p.type) + ';');
    }
    lines.push('}');
    lines.push('');
    lines.push('export interface ' + name + 'Result {');
    lines.push('  data: ' + toTs(schema.return_type) + ';');
    lines.push('}');
    lines.push('');
  }
  lines.push('export interface Types {');
  for (var k = 0; k < names.length; k++) {
    lines.push('  ' + names[k] + ': { params: ' + names[k] + 'Params; result: ' + names[k] + 'Result };');
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function fetchSchema(url) {
  var endpoint = url.replace(/\/+$/, '');
  if (endpoint.indexOf('/rpc') !== endpoint.length - 4) {
    endpoint += '/rpc';
  }
  if (typeof fetch !== 'undefined') {
    return fetch(endpoint).then(function(res) {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return res.json();
    });
  }
  var mod = url.indexOf('https') === 0 ? require('https') : require('http');
  return new Promise(function(resolve, reject) {
    mod.get(endpoint, function(res) {
      var data = '';
      res.on('data', function(c) { data += c; });
      res.on('end', function() {
        if (res.statusCode !== 200) return reject(new Error('HTTP ' + res.statusCode));
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(e); }
      });
    }).on('error', reject);
  });
}

function main() {
  var isInteractive = process.stdin.isTTY;
  var envUrl = process.env.PYRPC_URL;
  var url = null;

  if (isInteractive) {
    var rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    return new Promise(function(resolve) {
      rl.question('  pyRPC backend URL (default: http://localhost:8000): ', function(answer) {
        rl.close();
        url = answer.trim() || 'http://localhost:8000';
        resolve(url);
      });
    }).then(function(url) {
      return fetchSchema(url).then(function(schemas) {
        var code = generate(schemas);
        fs.mkdirSync(path.dirname(TYPES_FILE), { recursive: true });
        fs.writeFileSync(TYPES_FILE, code, 'utf-8');
        console.log('  \u2713 @pyrpc/types: generated for ' + Object.keys(schemas).length + ' procedures');
        console.log('  Import: import type { Types } from "@pyrpc/types"');
      }).catch(function(err) {
        console.log('  \u2717 @pyrpc/types: could not connect (' + err.message + ')');
        console.log('  Run manually: pyrpc codegen ' + url);
      });
    });
  }

  if (envUrl) {
    return fetchSchema(envUrl).then(function(schemas) {
      var code = generate(schemas);
      fs.mkdirSync(path.dirname(TYPES_FILE), { recursive: true });
      fs.writeFileSync(TYPES_FILE, code, 'utf-8');
      console.log('  \u2713 @pyrpc/types: generated for ' + Object.keys(schemas).length + ' procedures');
    }).catch(function(err) {
      console.log('  \u2717 @pyrpc/types: could not connect (' + err.message + ')');
      console.log('  Run manually: pyrpc codegen ' + envUrl);
    });
  }

  console.log('');
  console.log('  \u26A1 @pyrpc/types: no types generated yet.');
  console.log('  To connect to your pyRPC backend:');
  console.log('    pyrpc codegen http://localhost:8000');
  console.log('  Or install interactively in a terminal:');
  console.log('    npm install @pyrpc/client');
  console.log('');
  return Promise.resolve();
}

main().catch(function(e) {});
