[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyrpc-workspace"
version = "0.6.2"
description = "pyRPC Monorepo Workspace"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-asyncio>=0.25.0",
    "fastapi>=0.100.0",
    "flask>=3.0.0",
    "httpx>=0.24.0",
    "typer>=0.9.0",
    "rich>=13.0.0",
    "jinja2>=3.1.0",
    "uvicorn>=0.23.0",
    "anyio>=4.0",
    "pydantic>=2.0",
]



[tool.uv.workspace]
members = [
    "packages/pyrpc-core",
    "packages/pyrpc-codegen",
    "packages/pyrpc-fastapi",
    "packages/pyrpc-flask",
]

[tool.uv.sources]
pyrpc-core = { workspace = true }
pyrpc-flask = { workspace = true }
pyrpc-fastapi = { workspace = true }
pyrpc-codegen = { workspace = true }


[tool.hatch.build.targets.wheel]
bypass-selection = true

[tool.ruff]
select = ["E", "F", "B", "I"]
line-length = 88
target-version = "py311"

[tool.pytest.ini_options]
testpaths = [
    "packages/pyrpc-core/tests",
    "packages/pyrpc-fastapi/tests",
    "packages/pyrpc-flask/tests",
    "packages/pyrpc-codegen/tests",
]
pythonpath = [
    "packages/pyrpc-core/src",
    "packages/pyrpc-fastapi/src",
    "packages/pyrpc-flask/src",
    "packages/pyrpc-codegen/src"
]
asyncio_mode = "auto"

[dependency-groups]
dev = [
    "fastapi>=0.128.7",
    "flask>=3.1.2",
    "jinja2>=3.1.6",
    "pydantic-core==2.41.5",
    "pyrpc-codegen",
    "pyrpc-fastapi",
    "pytest>=9.0.2",
    "pytest-asyncio>=0.25.0",
    "rich>=14.3.2",
    "typer>=0.21.1",
    "uvicorn>=0.40.0",
]
