import type { Types } from '@pyrpc/types';
import { createNextClient } from '@pyrpc/next';

/**
 * The single pyRPC api object for this Next.js app.
 *
 * - Use `api.*` for React hooks in Client Components
 * - Use `api.prefetch.*` in Server Components / page.tsx
 * - Wrap your layout with `<api.Provider>` (done in providers.tsx)
 *
 * Types are generated by `pyrpc dev` into src/__pyrpc.d.ts and resolved
 * here via the "@pyrpc/types" tsconfig paths alias.
 */
export const api = createNextClient<Types>({
  baseUrl: process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000',
});
