import Link from 'next/link'

export default function TheGeneratedFileContractPage() {
    return (
        <article className="max-w-3xl mx-auto px-6 py-20">
            <div className="mb-12">
                <Link href="/blog" className="text-[10px] font-mono uppercase tracking-[0.2em] text-fd-muted-foreground hover:text-fd-foreground transition-colors">
                    &larr; Back to Blog
                </Link>
                <h1 className="text-2xl font-bold tracking-tight mt-6 mb-3">
                    The generated file's contract
                </h1>
                <div className="flex items-center gap-3 text-[10px] font-mono uppercase tracking-wider text-fd-muted-foreground">
                    <time>August 12, 2026 at 9:20am</time>
                    <span>&middot;</span>
                    <span>5 min read</span>
                </div>
            </div>

            <section className="prose dark:prose-invert max-w-none text-sm leading-relaxed space-y-5 text-fd-muted-foreground [&_strong]:text-fd-foreground">
                <p>
                    Open any generated <code className="text-[10px] font-mono bg-fd-muted px-1.5 py-0.5 rounded">__pyrpc.ts</code> and the first thing you see is a long comment. It is not decoration. The header is a written contract between pyrpc and your project, and since v0.12.0 it documents things that were previously implicit.
                </p>

                <h2 className="text-lg font-bold tracking-tight text-fd-foreground mt-10">The header, line by line</h2>
                <pre className="bg-fd-muted p-4 rounded-lg overflow-x-auto text-[11px] leading-relaxed">
{`/**
 * Auto-generated by pyrpc dev — do not edit by hand.
 * Re-generated automatically whenever your Python procedures change.
 *
 * This file is a real runtime module: it carries both the compile-time
 * procedure types and the runtime procedure-kind map (\`procedureKinds\`).
 *
 * Resolved via tsconfig.json paths alias:
 *   "paths": { "@pyrpc/types": ["./__pyrpc.ts"] }
 *
 * Bundlers that don't honor tsconfig paths for imports inside node_modules
 * (Vite, SvelteKit, Next.js Turbopack) must alias "@pyrpc/types" to this file
 * explicitly — pyrpc dev configures this for known frameworks automatically.
 *
 * Usage:
 * \`\`\`ts
 * import type { Types } from "@pyrpc/types"
 * import { createNextClient } from "@pyrpc/next"
 * ...\`\`\`
 */`}
                </pre>
                <p>
                    Four commitments are being made here.
                </p>

                <h2 className="text-lg font-bold tracking-tight text-fd-foreground mt-10">1. Ownership: "do not edit by hand"</h2>
                <p>
                    The file is owned by codegen. Edits will be overwritten on the next regen. This is not a threat — it is a fact the author needs to know before they tweak a type and lose it. The <code className="text-[10px] font-mono bg-fd-muted px-1.5 py-0.5 rounded">eslint-disable</code> pragma at the top reinforces it: this file opts out of your lint rules because your rules do not apply to machine output.
                </p>

                <h2 className="text-lg font-bold tracking-tight text-fd-foreground mt-10">2. Lifetime: "re-generated whenever procedures change"</h2>
                <p>
                    The contract states <em>when</em> the file changes. The dev watcher regenerates on edits and module reloads. Knowing the invalidation trigger lets a developer reason about why their types look stale — usually a procedure changed and the watcher had not fired yet, not a bug in their code.
                </p>

                <h2 className="text-lg font-bold tracking-tight text-fd-foreground mt-10">3. Resolution: how @pyrpc/types finds this file</h2>
                <p>
                    The header documents the two-layer resolution story. First, the tsconfig <code className="text-[10px] font-mono bg-fd-muted px-1.5 py-0.5 rounded">paths</code> alias maps <code className="text-[10px] font-mono bg-fd-muted px-1.5 py-0.5 rounded">@pyrpc/types</code> to this file for the compiler. Second — and this is the v0.12.0 addition — bundlers that do not honor tsconfig paths for imports inside node_modules need an explicit alias. The header names the offenders (Vite, SvelteKit, Next.js Turbopack) so the failure mode is diagnosable from the artifact itself.
                </p>

                <h2 className="text-lg font-bold tracking-tight text-fd-foreground mt-10">4. Usage: how to consume it</h2>
                <p>
                    The usage example shows the intended import pattern — <code className="text-[10px] font-mono bg-fd-muted px-1.5 py-0.5 rounded">import type &#123; Types &#125; from "@pyrpc/types"</code>, never a relative path to the file. The import surface is stable even though the artifact changes.
                </p>

                <h2 className="text-lg font-bold tracking-tight text-fd-foreground mt-10">Why the header matters</h2>
                <p>
                    Generated files are the most-debugged artifacts you never write. The header is the first thing a confused developer reads, and a good header pre-answers their questions: who owns this, when does it change, how is it wired, and how do I use it. Keeping that contract inside the file means the answer travels with the artifact instead of living in docs nobody reads.
                </p>
            </section>
        </article>
    )
}
