import { highlight } from "fumadocs-core/highlight";
import type { HighlightOptions } from "fumadocs-core/highlight";
import type { ReactNode } from "react";

import { shikiHighlightOptions } from "@/lib/shiki-themes";

const snippet1Code = `from pyrpc_core import rpc

@rpc
def greet(name: str) -> str:
    return f"Hello {name}!"`;

const snippet2Code = `/**
 * Auto-generated by pyrpc dev.
 */

export interface Types {
  greet(name: string): Promise<string>;
}`;

const snippet3Code = `import { createClient, httpLink } from "@pyrpc/client";
import type { Types } from "@pyrpc/types";

const client = createClient<Types>({
  links: [httpLink({ url: "https://api.example.com" })],
});

const result = await client.greet("World");
console.log(result); // "Hello World!"`;

async function highlightSnippet(code: string, lang: string) {
  return highlight(code, {
    lang,
    ...shikiHighlightOptions,
    components: {
      pre: ({ children, className, style }: { children?: ReactNode; className?: string; style?: Record<string, string> }) => (
        <div className={className} style={style}>{children}</div>
      ),
    },
  } satisfies HighlightOptions);
}

export async function QuickstartSnippet1() {
  return highlightSnippet(snippet1Code, "python");
}

export async function QuickstartSnippet2() {
  return highlightSnippet(snippet2Code, "typescript");
}

export async function QuickstartSnippet3() {
  return highlightSnippet(snippet3Code, "typescript");
}
