import { highlight } from "fumadocs-core/highlight";
import type { HighlightOptions } from "fumadocs-core/highlight";
import type { ReactNode } from "react";

import { shikiHighlightOptions } from "@/lib/shiki-themes";

export const SNIPPET_1_TEXT = `from pyrpc_core import rpc, model

@model
class User:
    name: str

@rpc
def greet(name: str) -> User:
    return User(name=name)`;

export const SNIPPET_2_TEXT = `/**
 * Auto-generated by pyrpc dev; do not edit by hand.
 */
// ── Procedures ──────────────────────────────────────────
export interface User {
  name: string;
}

export type Types = {
  /**
   * Greets a user by name.
   * @kind query
   */
  greet: ((name: string) => Promise<User>) & {
    readonly _pyrpcKind: "query";
  };
}`;

export const SNIPPET_3_TEXT = `import { createClient, httpBatchLink } from "@pyrpc/client";
import type { Types } from "@pyrpc/types";

const api = createClient<Types>({
  links: [
    httpBatchLink({
      url: "https://api.example.com",
    }),
  ],
});

const user = await api.greet({ name: "World" });
console.log(user.name); // fully typed as string`;

const snippet1Code = SNIPPET_1_TEXT;

const snippet2Code = SNIPPET_2_TEXT;

const snippet3Code = SNIPPET_3_TEXT;

async function highlightSnippet(code: string, lang: string) {
  return highlight(code, {
    lang,
    ...shikiHighlightOptions,
    // Emit only --shiki-light/--shiki-dark variables (no inline colors) so
    // fumadocs' preset stylesheet can swap token colors under `.dark`.
    defaultColor: false,
    components: {
      pre: ({ children, className, style }: { children?: ReactNode; className?: string; style?: Record<string, string> }) => (
        <div
          className={className}
          // The code window provides its own theme-aware surface; shiki's
          // inline light-theme background would paint a second one on top.
          style={{ ...style, backgroundColor: undefined }}
        >
          {children}
        </div>
      ),
    },
  } satisfies HighlightOptions);
}

export async function QuickstartSnippet1() {
  return highlightSnippet(snippet1Code, "python");
}

export async function QuickstartSnippet2() {
  return highlightSnippet(snippet2Code, "typescript");
}

export async function QuickstartSnippet3() {
  return highlightSnippet(snippet3Code, "typescript");
}
