name: Publish

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for Trusted Publishing
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install build tools
        run: pip install build
        
      - name: Build python packages
        run: |
          python -m build packages/pyrpc-core
          python -m build packages/pyrpc-codegen
          python -m build packages/pyrpc-fastapi
          python -m build packages/pyrpc-flask
          
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: packages/*/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        working-directory: ./packages/client
        run: npm install
        
      - name: Build TypeScript package
        working-directory: ./packages/client
        run: npm run build
        
      - name: Publish to npm
        working-directory: ./packages/client
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
